# nvfetcher.toml
[sf-pro]
src.git = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts"
fetch.github = "sahibjotsaggu/San-Francisco-Pro-Fonts"
[x11-emoji-picker]
src.git = "https://github.com/GaZaTu/x11-emoji-picker"
fetch.github = "GaZaTu/x11-emoji-picker"
[picom-git]
src.git = "https://github.com/yshui/picom"
fetch.github = "yshui/picom"
git.fetchSubmodules = true
[picom-jonaburg-git]
src.git = "https://github.com/jonaburg/picom"
fetch.github = "jonaburg/picom"
git.fetchSubmodules = true
[picom-arian8j2-git]
src.git = "https://github.com/Arian8j2/picom"
fetch.github = "Arian8j2/picom"
git.fetchSubmodules = true
[tokyo-night-gtk-theme]
src.git = "https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme"
fetch.github = "Fausto-Korpsvart/Tokyo-Night-GTK-Theme"
[bspwm-rounded-corners]
src.git = "https://github.com/j-james/bspwm-rounded-corners"
fetch.github = "j-james/bspwm-rounded-corners"