# nvfetcher.toml
[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"
[sf-pro]
src.git = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts"
fetch.github = "sahibjotsaggu/San-Francisco-Pro-Fonts"
[picom-jonaburg-git]
src.git = "https://github.com/jonaburg/picom"
fetch.github = "jonaburg/picom"