#!/bin/sh

# ##############################################################################
# #                                  ENV VARS                                  #
# ##############################################################################

export WALLPAPER="$HOME/.config/bspwm/assets/wallpaper.png"
export LOCKSCREEN_WALLPAPER="$HOME/.config/bspwm/assets/lockscreen.png"

# ##############################################################################
# #                                  FUNCTIONS                                 #
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# Clear cache.
rm $HOME/.cache/dunst.log
rm $HOME/.cache/fake_battery_capacity
rm $HOME/.cache/eww-calendar.lock
rm $HOME/.cache/eww-escreen.lock
rm $HOME/.cache/eww-control-center.lock
rm -r $HOME/.cache/dunst/

# Fix cursor size.
xsetroot -cursor_name left_ptr

# Autostart applications.
pkill dunst &
eww open bar &
picom --config $HOME/.config/picom/picom.conf &
dunst --config $HOME/.config/dunst/dunstrc &
ferdium &

# Start polkit agent.
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Setup wallpaper.
# hsetroot -fill "$WALLPAPER"
hsetroot -solid "#1C2325"

# I hate mouse drift.
xset m 0 0

# Fix for eww bar not hiding on a fullscreen window.
pkill ewwFullscreenFix.sh; $HOME/.config/bspwm/scripts/ewwFullscreenFix.sh &
# Make Do Not Disturb and Night Light work after power on or reboot.
pkill persistentQuickUtilities.sh; $HOME/.config/bspwm/scripts/persistentQuickUtilities.sh &

# Start MPD and mpDris2
# exec mpd &
# exec mpDris2 &

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc config border_width         4
bspc config window_gap          12
bspc config active_border_color \#7ba5dd
bspc config focused_border_color \#7ba5dd
bspc config normal_border_color \#9fa0a0

bspc monitor -d 1 2 3 4 5

rule Brave-browser                  desktop=1
rule Code                           desktop=2
rule Steam                          desktop=4
rule discord                        desktop=5 follow=off
rule Chromium-browser               desktop=5 follow=off
rule Ferdium               desktop=5 follow=off

rule Viewnior                       state=floating
rule mpv                            state=fullscreen follow=on

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

config pointer_modifier             Mod4

config window_gap                   16

config top_padding                  48
config left_padding                 0
config right_padding                0
config bottom_padding               0

config split_ratio                  0.62
config borderless_monocle           true
config gapless_monocle              true

# ##############################################################################
# #                                 MISCELLANEOUS                              #
# ##############################################################################

# Fix windows being below bar
xdo lower -N eww-bar
amixer sset 'Master' 50%
$HOME/.config/sxhkd/scripts/touchpadToggle.sh

