# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  my-bspwm-custom-fonts = {
    pname = "my-bspwm-custom-fonts";
    version = "1.0";
    src = fetchurl {
      url = "https://github.com/eekrain/dotfiles/releases/download/v1.0/my_bspwm_custom_fonts.tar.xz";
      sha256 = "sha256-J2xoO1hAnKkbRAMUKKuDJ85DBGRCHSIeDIiDD1+PSS8=";
    };
  };
  nhost-cli = {
    pname = "nhost-cli";
    version = "v0.8.4";
    src = fetchurl {
      url = "https://github.com/nhost/cli/releases/download/v0.8.4/cli-v0.8.4-linux-amd64.tar.gz";
      sha256 = "sha256-mwK1jtvd/vhCfxw2ctGqN/sLUSHgvtR+fvh0TzJjVGQ=";
    };
  };
  picom-arian8j2-git = {
    pname = "picom-arian8j2-git";
    version = "ce46b21a39ae79a727768514cb00e632cbfa9483";
    src = fetchFromGitHub ({
      owner = "Arian8j2";
      repo = "picom";
      rev = "ce46b21a39ae79a727768514cb00e632cbfa9483";
      fetchSubmodules = true;
      sha256 = "sha256-3tjPGr84SGtM3HD+AttPSC4h6BfDiy1RGoRyigd7Hpw=";
    });
    date = "2022-09-29";
  };
  picom-git = {
    pname = "picom-git";
    version = "8a373c38a631e0344c38d3b19ab673aacfbaf1f5";
    src = fetchFromGitHub ({
      owner = "yshui";
      repo = "picom";
      rev = "8a373c38a631e0344c38d3b19ab673aacfbaf1f5";
      fetchSubmodules = true;
      sha256 = "sha256-mKtop5/80YIAZqogshk5Tm9PR+93rLWSh8hqtNFjlPE=";
    });
    date = "2022-10-10";
  };
  picom-jonaburg-git = {
    pname = "picom-jonaburg-git";
    version = "e3c19cd7d1108d114552267f302548c113278d45";
    src = fetchFromGitHub ({
      owner = "jonaburg";
      repo = "picom";
      rev = "e3c19cd7d1108d114552267f302548c113278d45";
      fetchSubmodules = true;
      sha256 = "sha256-4voCAYd0fzJHQjJo4x3RoWz5l3JJbRvgIXn1Kg6nz6Y=";
    });
    date = "2022-03-19";
  };
  sf-pro = {
    pname = "sf-pro";
    version = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
    src = fetchFromGitHub ({
      owner = "sahibjotsaggu";
      repo = "San-Francisco-Pro-Fonts";
      rev = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
      fetchSubmodules = false;
      sha256 = "sha256-mAXExj8n8gFHq19HfGy4UOJYKVGPYgarGd/04kUIqX4=";
    });
    date = "2021-06-22";
  };
  tokyo-night-gtk-theme = {
    pname = "tokyo-night-gtk-theme";
    version = "517716f1da4520e9db37c7d86907c54f76dfb936";
    src = fetchFromGitHub ({
      owner = "Fausto-Korpsvart";
      repo = "Tokyo-Night-GTK-Theme";
      rev = "517716f1da4520e9db37c7d86907c54f76dfb936";
      fetchSubmodules = false;
      sha256 = "sha256-fGjFKEOL9F1bFWRBKC1tJfDWIucRoU04YNHGuVlcrLQ=";
    });
    date = "2022-10-12";
  };
  x11-emoji-picker = {
    pname = "x11-emoji-picker";
    version = "7650a30914fc4fe0ca332d7674f9206bef408e4e";
    src = fetchFromGitHub ({
      owner = "GaZaTu";
      repo = "x11-emoji-picker";
      rev = "7650a30914fc4fe0ca332d7674f9206bef408e4e";
      fetchSubmodules = false;
      sha256 = "sha256-GqQvjUegQqqhVx5gujO3eDw8w5ib0hrEI7XbHS8Aa3U=";
    });
    date = "2022-03-10";
  };
}
